import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ApolloWrapper from "@/components/ApolloWrapper";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} antialiased`}>
        <div className="w-full mx-auto flex flex-col max-w-7xl min-h-dvh bg-grey-50 px-4 pb-12 ">
          <Header />
          <ApolloWrapper>{children}</ApolloWrapper>
        </div>
        <Footer />
      </body>
    </html>
  );
}
